kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.app_name }}-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.resources.storage_requests }}
