kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ .Values.app_name }}
  labels:
    app: {{ .Values.app_name }}
spec:
  host: {{ .Values.app_host }}
  to:
    kind: Service
    name: {{ .Values.app_name }}
    weight: 100
  port:
    targetPort: 9000
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Allow
  wildcardPolicy: None
status:
  ingress:
    - host: {{ .Values.app_host }}
      routerName: default
      wildcardPolicy: None
